services:
  appdb:
    image: postgres
    restart: always
    env_file:
      - .env # This config applies inside the conainer only. Run docker-compose --env-file .env up
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${APP_DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - appdb:/var/lib/postgres
      - ./create-app-db.sql:/docker-entrypoint-initdb.d/create_database.sql
volumes:
  appdb:
